# Generated by Django 4.2.7 on 2026-01-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category__display_order', 'name']},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='notes',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.TextField(default='Bangalore'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(default='contact@kakacafe.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='KAKA CAFE', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(default='7022470962', max_length=20),
        ),
    ]
